import { productAPI, userAPI, orderAPI, chatAPI } from './api';

// ==================== USERS SEED DATA ====================

const sampleUsers = [
  {
    email: 'admin@urtree.com',
    password: 'admin123',
    name: 'Admin UrTree',
    role: 'admin'
  },
  // Sellers
  {
    email: 'seller1@example.com',
    password: 'seller123',
    name: 'Budi Santoso',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Toko Tanaman Hijau',
    shopDescription: 'Menyediakan tanaman hias berkualitas tinggi dengan harga terjangkau. Sudah melayani 1000+ pelanggan.',
    shopAddress: 'Jl. Raya Jakarta No. 123',
    shopCity: 'Jakarta Selatan',
    phone: '081234567890',
    sellerRating: 4.8,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
  },
  {
    email: 'seller2@example.com',
    password: 'seller123',
    name: 'Siti Rahayu',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Green Paradise',
    shopDescription: 'Spesialis tanaman hias indoor dan outdoor. Gratis konsultasi perawatan tanaman!',
    shopAddress: 'Jl. Setia Budi No. 45',
    shopCity: 'Bandung',
    phone: '082345678901',
    sellerRating: 4.9,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
  },
  {
    email: 'seller3@example.com',
    password: 'seller123',
    name: 'Ahmad Wijaya',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Benih Nusantara',
    shopDescription: 'Supplier benih sayuran dan buah organik terlengkap. Kualitas terjamin!',
    shopAddress: 'Jl. Tanjung Perak No. 78',
    shopCity: 'Surabaya',
    phone: '083456789012',
    sellerRating: 4.7,
  },
  {
    email: 'seller4@example.com',
    password: 'seller123',
    name: 'Dewi Lestari',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Tani Makmur',
    shopDescription: 'Peralatan berkebun lengkap untuk pemula hingga profesional.',
    shopAddress: 'Jl. Malioboro No. 56',
    shopCity: 'Yogyakarta',
    phone: '084567890123',
    sellerRating: 4.6,
  },
  {
    email: 'seller5@example.com',
    password: 'seller123',
    name: 'Rudi Hermawan',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Kebun Organik',
    shopDescription: 'Produk organik untuk kebun sehat dan ramah lingkungan.',
    shopAddress: 'Jl. Pajajaran No. 89',
    shopCity: 'Bogor',
    phone: '085678901234',
    sellerRating: 4.8,
  },
  {
    email: 'seller6@example.com',
    password: 'seller123',
    name: 'Linda Kusuma',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Flora Cantik',
    shopDescription: 'Tanaman bunga hias dan tanaman langka koleksi pribadi.',
    shopAddress: 'Jl. Diponegoro No. 34',
    shopCity: 'Semarang',
    phone: '086789012345',
    sellerRating: 4.9,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
  },
  {
    email: 'seller7@example.com',
    password: 'seller123',
    name: 'Eko Prasetyo',
    role: 'seller',
    hasSellerAccount: true,
    shopName: 'Sukses Tani',
    shopDescription: 'Benih dan bibit unggul untuk hasil panen maksimal.',
    shopAddress: 'Jl. Ahmad Yani No. 67',
    shopCity: 'Malang',
    phone: '087890123456',
    sellerRating: 4.7,
  },
  // Buyers
  {
    email: 'buyer1@example.com',
    password: 'buyer123',
    name: 'Andi Kurniawan',
    role: 'buyer',
    address: 'Jl. Sudirman No. 12',
    city: 'Jakarta Pusat',
    phone: '081111222333',
  },
  {
    email: 'buyer2@example.com',
    password: 'buyer123',
    name: 'Maya Sari',
    role: 'buyer',
    address: 'Jl. Gatot Subroto No. 45',
    city: 'Jakarta Selatan',
    phone: '082222333444',
  },
  {
    email: 'buyer3@example.com',
    password: 'buyer123',
    name: 'Rizky Pratama',
    role: 'buyer',
    address: 'Jl. Dago No. 78',
    city: 'Bandung',
    phone: '083333444555',
  },
];

// ==================== PRODUCTS SEED DATA ====================

const sampleProducts = [
  // ===== TANAMAN HIDUP - INDOOR (20 products) =====
  {
    name: 'Monstera Deliciosa',
    description: 'Tanaman hias indoor populer dengan daun besar berlubang unik. Cocok untuk ruangan dengan cahaya sedang. Mudah perawatan dan tahan lama. Memberikan kesan tropis pada ruangan Anda.',
    price: 150000,
    stock: 25,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '1thn+',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 45,
  },
  {
    name: 'Philodendron Birkin',
    description: 'Tanaman hias cantik dengan garis putih pada daunnya yang khas. Mudah perawatan dan tahan banting. Cocok untuk indoor dengan cahaya tidak langsung.',
    price: 250000,
    stock: 15,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1593482892540-73c9199dbe3f?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '1thn+',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 32,
  },
  {
    name: 'Aglaonema Red Anjamani',
    description: 'Tanaman hias dengan warna merah mencolok yang menarik perhatian. Tahan di ruangan ber-AC dan minim cahaya. Pembersih udara alami yang cantik.',
    price: 180000,
    stock: 30,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 56,
  },
  {
    name: 'Sansevieria Trifasciata (Lidah Mertua)',
    description: 'Tanaman pembersih udara yang sangat mudah dirawat. Cocok untuk pemula. Tahan dengan cahaya minim dan tidak perlu sering disiram. NASA certified air purifier!',
    price: 85000,
    stock: 50,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1593482892585-62f5ea18d6c5?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 78,
  },
  {
    name: 'Sirih Gading (Pothos)',
    description: 'Tanaman merambat yang mudah tumbuh. Cocok untuk hanging pot atau rak. Membersihkan udara dengan efektif dan tumbuh cepat.',
    price: 45000,
    stock: 40,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 92,
  },
  {
    name: 'Calathea Ornata',
    description: 'Tanaman dengan motif daun yang indah seperti lukisan. Daun bergerak mengikuti cahaya (prayer plant). Cocok untuk indoor dengan humidity tinggi.',
    price: 120000,
    stock: 20,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1597147365155-c29c0a9e6c71?w=800'],
    sellerId: 'seller6@example.com',
    sellerName: 'Flora Cantik',
    sellerRating: 4.9,
    sellerLocation: 'Semarang',
    plantAge: '<1thn',
    maxDeliveryRadius: 40,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
    sold: 23,
  },
  {
    name: 'Alocasia Polly (African Mask)',
    description: 'Tanaman eksotis dengan daun berbentuk seperti topeng Afrika. Warna hijau gelap dengan urat putih mencolok. Statement plant yang mewah.',
    price: 175000,
    stock: 12,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1617478755490-e21232a5eeaf?w=800'],
    sellerId: 'seller6@example.com',
    sellerName: 'Flora Cantik',
    sellerRating: 4.9,
    sellerLocation: 'Semarang',
    plantAge: '<1thn',
    maxDeliveryRadius: 40,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
    sold: 18,
  },
  {
    name: 'Anthurium Jari',
    description: 'Anthurium dengan daun menjari yang unik. Tanaman langka dan bernilai tinggi. Cocok untuk kolektor tanaman hias.',
    price: 350000,
    stock: 8,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800'],
    sellerId: 'seller6@example.com',
    sellerName: 'Flora Cantik',
    sellerRating: 4.9,
    sellerLocation: 'Semarang',
    plantAge: '1thn+',
    maxDeliveryRadius: 40,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
    sold: 12,
  },
  {
    name: 'Pilea Peperomioides (Chinese Money Plant)',
    description: 'Tanaman unik dengan daun bulat seperti koin. Membawa keberuntungan menurut feng shui. Mudah diperbanyak dan dirawat.',
    price: 95000,
    stock: 28,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1590431306498-8cf993d1c83d?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '<1thn',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 34,
  },
  {
    name: 'Ficus Lyrata (Fiddle Leaf Fig)',
    description: 'Tanaman trendy dengan daun besar berbentuk biola. Favorit interior designer. Memerlukan cahaya terang tidak langsung.',
    price: 280000,
    stock: 10,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1621264266023-abcd123a39a6?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '1thn+',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 15,
  },
  {
    name: 'Maranta Leuconeura (Prayer Plant)',
    description: 'Tanaman dengan motif daun merah dan hijau yang indah. Daun akan melipat di malam hari seperti berdoa. Cocok untuk indoor lembab.',
    price: 110000,
    stock: 18,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1597045566677-5ee9d29588ae?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 27,
  },
  {
    name: 'Syngonium Podophyllum Pink',
    description: 'Tanaman dengan daun berwarna pink dan hijau yang cantik. Mudah tumbuh dan cocok untuk hanging basket. Tahan dengan berbagai kondisi cahaya.',
    price: 75000,
    stock: 35,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1608806322283-b3f91322c2c1?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 51,
  },
  {
    name: 'Scindapsus Pictus (Satin Pothos)',
    description: 'Sirih beludru dengan bintik perak pada daun. Tanaman merambat yang elegant. Tahan banting dan cocok untuk pemula.',
    price: 65000,
    stock: 42,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1509423350716-97f9360b4e09?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '<1thn',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 68,
  },
  {
    name: 'Zamioculcas Zamiifolia (ZZ Plant)',
    description: 'Tanaman super tahan banting! Bisa bertahan tanpa air hingga 3 minggu. Cocok untuk yang sering lupa menyiram. Daun mengkilap sangat cantik.',
    price: 130000,
    stock: 22,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1593482892585-62f5ea18d6c5?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '1thn+',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 41,
  },
  {
    name: 'Hoya Carnosa (Wax Plant)',
    description: 'Tanaman merambat dengan bunga cantik berbentuk bintang. Daun tebal seperti lilin. Aroma bunga harum di malam hari.',
    price: 145000,
    stock: 14,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1604892645792-e137ce0e2e42?w=800'],
    sellerId: 'seller6@example.com',
    sellerName: 'Flora Cantik',
    sellerRating: 4.9,
    sellerLocation: 'Semarang',
    plantAge: '1thn+',
    maxDeliveryRadius: 40,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
    sold: 19,
  },
  {
    name: 'Peperomia Obtusifolia',
    description: 'Tanaman kecil dengan daun tebal mengkilap. Sangat mudah dirawat dan cocok untuk meja kerja. Tidak memerlukan banyak air.',
    price: 55000,
    stock: 48,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1586078493191-8e61a5e1e4d7?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '<1thn',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 73,
  },
  {
    name: 'Dieffenbachia (Daun Bahagia)',
    description: 'Tanaman dengan motif daun putih dan hijau yang indah. Membawa kebahagiaan di rumah. Tumbuh cepat dan mudah perawatan.',
    price: 90000,
    stock: 26,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1614594975525-e45190c55d0b?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '<1thn',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 38,
  },
  {
    name: 'Dracaena Marginata',
    description: 'Tanaman dengan bentuk seperti pohon mini. Daun panjang dengan pinggiran merah. Pembersih udara yang efektif.',
    price: 135000,
    stock: 16,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1596420387376-aa9e96c3257f?w=800'],
    sellerId: 'seller1@example.com',
    sellerName: 'Toko Tanaman Hijau',
    sellerRating: 4.8,
    sellerLocation: 'Jakarta Selatan',
    plantAge: '1thn+',
    maxDeliveryRadius: 50,
    sellerLat: -6.2615,
    sellerLng: 106.8106,
    sold: 29,
  },
  {
    name: 'Aspidistra Elatior (Cast Iron Plant)',
    description: 'Tanaman super tahan banting! Bisa hidup di kondisi minim cahaya. Cocok untuk area gelap di rumah. Perawatan minimal.',
    price: 100000,
    stock: 24,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1594671266423-1f89c3ff61cb?w=800'],
    sellerId: 'seller2@example.com',
    sellerName: 'Green Paradise',
    sellerRating: 4.9,
    sellerLocation: 'Bandung',
    plantAge: '1thn+',
    maxDeliveryRadius: 30,
    sellerLat: -6.9175,
    sellerLng: 107.6191,
    sold: 31,
  },
  {
    name: 'Begonia Maculata',
    description: 'Tanaman cantik dengan daun bintik-bintik putih dan punggung merah. Sangat instagramable! Bunga putih yang indah.',
    price: 125000,
    stock: 19,
    category: 'tanaman-hidup',
    images: ['https://images.unsplash.com/photo-1617478755490-e21232a5eeaf?w=800'],
    sellerId: 'seller6@example.com',
    sellerName: 'Flora Cantik',
    sellerRating: 4.9,
    sellerLocation: 'Semarang',
    plantAge: '<1thn',
    maxDeliveryRadius: 40,
    sellerLat: -6.9669,
    sellerLng: 110.4203,
    sold: 25,
  },

  // ===== BENIH (15 products) =====
  {
    name: 'Benih Tomat Cherry',
    description: 'Benih tomat cherry berkualitas tinggi. Cocok untuk ditanam di pot atau kebun rumah. Panen melimpah dalam 60-70 hari.',
    price: 25000,
    stock: 100,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 145,
  },
  {
    name: 'Benih Cabai Rawit',
    description: 'Benih cabai rawit super pedas. Hasil panen melimpah dan tahan hama. Cocok untuk iklim tropis Indonesia.',
    price: 30000,
    stock: 150,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1583852207954-b9f8b8094c91?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 178,
  },
  {
    name: 'Benih Bayam Hijau',
    description: 'Benih bayam hijau organik. Panen cepat 30-40 hari setelah tanam. Kaya nutrisi dan mudah tumbuh.',
    price: 15000,
    stock: 200,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 212,
  },
  {
    name: 'Benih Kangkung Darat',
    description: 'Benih kangkung darat kualitas premium. Tumbuh cepat dan tahan panas. Panen pertama 25-30 hari.',
    price: 12000,
    stock: 180,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 193,
  },
  {
    name: 'Benih Sawi Hijau',
    description: 'Benih sawi hijau organik. Cocok untuk hidroponik atau tanah. Panen dalam 40-45 hari setelah semai.',
    price: 18000,
    stock: 160,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1628773822503-930a7eaecf80?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 156,
  },
  {
    name: 'Benih Timun Jepang',
    description: 'Benih timun jepang renyah dan manis. Tahan penyakit dan produktivitas tinggi. Cocok untuk tabulampot.',
    price: 35000,
    stock: 90,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1604977042946-1eecc30f269e?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 87,
  },
  {
    name: 'Benih Terong Ungu',
    description: 'Benih terong ungu lokal. Buah besar dan lebat. Cocok untuk masakan Indonesia. Panen 70-80 hari.',
    price: 22000,
    stock: 120,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1615485290382-441e4d049cb5?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 98,
  },
  {
    name: 'Benih Buncis',
    description: 'Benih buncis hijau tipe merambat. Panen bisa hingga 3-4 bulan. Cocok untuk pekarangan rumah.',
    price: 20000,
    stock: 140,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1626082909233-e7b86e22e187?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 112,
  },
  {
    name: 'Benih Jagung Manis',
    description: 'Benih jagung manis berkualitas. Rasa super manis dan tekstur lembut. Panen 75-85 hari setelah tanam.',
    price: 28000,
    stock: 110,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1594735727133-9d46b4f5ed8a?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 76,
  },
  {
    name: 'Benih Melon Golden',
    description: 'Benih melon golden super manis. Daging tebal dan aroma harum. Cocok untuk lahan kering.',
    price: 45000,
    stock: 70,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1571575173700-afb9492441b3?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 54,
  },
  {
    name: 'Benih Selada Keriting',
    description: 'Benih selada keriting untuk hidroponik atau tanah. Tumbuh cepat 35-40 hari. Segar dan renyah.',
    price: 16000,
    stock: 175,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 167,
  },
  {
    name: 'Benih Bawang Merah',
    description: 'Benih bawang merah varietas lokal. Umbi besar dan tahan penyakit. Panen 60-70 hari.',
    price: 38000,
    stock: 95,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 82,
  },
  {
    name: 'Benih Kacang Panjang',
    description: 'Benih kacang panjang tipe tiang. Panen bisa berkali-kali. Cocok untuk pekarangan rumah.',
    price: 17000,
    stock: 155,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1626082909233-e7b86e22e187?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 128,
  },
  {
    name: 'Benih Wortel Import',
    description: 'Benih wortel import dari Jepang. Warna orange cerah dan rasa manis. Cocok untuk jus dan salad.',
    price: 32000,
    stock: 85,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1598170845058-32b9d6a5da37?w=800'],
    sellerId: 'seller3@example.com',
    sellerName: 'Benih Nusantara',
    sellerRating: 4.7,
    sellerLocation: 'Surabaya',
    sold: 71,
  },
  {
    name: 'Benih Paprika Merah',
    description: 'Benih paprika merah berkualitas. Buah besar dan tebal. Cocok untuk greenhouse atau polybag.',
    price: 42000,
    stock: 65,
    category: 'benih',
    images: ['https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800'],
    sellerId: 'seller7@example.com',
    sellerName: 'Sukses Tani',
    sellerRating: 4.7,
    sellerLocation: 'Malang',
    sold: 48,
  },

  // ===== PERALATAN & MEDIA TANAM (20 products) =====
  {
    name: 'Sekop Tangan Premium',
    description: 'Sekop tangan stainless steel berkualitas tinggi. Ergonomis dan tahan karat. Handle nyaman untuk pemakaian lama.',
    price: 45000,
    stock: 75,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 89,
  },
  {
    name: 'Pupuk Organik Kompos 5kg',
    description: 'Pupuk kompos organik alami dari sampah dapur. Kaya nutrisi untuk tanaman. Ramah lingkungan dan aman.',
    price: 35000,
    stock: 120,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 156,
  },
  {
    name: 'Pot Keramik Minimalis 20cm',
    description: 'Pot keramik dengan desain minimalis modern. Tersedia lubang drainase. Cocok untuk tanaman indoor.',
    price: 65000,
    stock: 60,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 92,
  },
  {
    name: 'Media Tanam Cocopeat 5kg',
    description: 'Media tanam dari sabut kelapa. Ringan, steril, dan menyerap air dengan baik. Cocok untuk semua jenis tanaman.',
    price: 40000,
    stock: 100,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 134,
  },
  {
    name: 'Gunting Tanaman Profesional',
    description: 'Gunting tanaman tajam dan presisi. Stainless steel anti karat. Cocok untuk pemangkasan dan panen.',
    price: 75000,
    stock: 45,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 67,
  },
  {
    name: 'Pupuk NPK Organik 1kg',
    description: 'Pupuk NPK lengkap untuk pertumbuhan optimal. Cocok untuk fase vegetatif dan generatif. Slow release formula.',
    price: 28000,
    stock: 150,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 178,
  },
  {
    name: 'Pot Plastik Set 10pcs',
    description: 'Set 10 pot plastik ukuran 15cm. Ringan dan tahan lama. Lubang drainase sudah tersedia. Cocok untuk pembibitan.',
    price: 35000,
    stock: 80,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 112,
  },
  {
    name: 'Sekop Besar Stainless',
    description: 'Sekop besar untuk lahan. Handle kayu yang kuat. Stainless steel tahan karat dan awet bertahun-tahun.',
    price: 125000,
    stock: 35,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 43,
  },
  {
    name: 'Sprayer 2 Liter',
    description: 'Sprayer manual kapasitas 2 liter. Nozzle adjustable untuk berbagai kebutuhan. Cocok untuk penyiraman dan penyemprotan pupuk.',
    price: 55000,
    stock: 70,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 78,
  },
  {
    name: 'Pupuk Kandang Kambing 10kg',
    description: 'Pupuk kandang kambing berkualitas sudah difermentasi. Kaya nitrogen dan mikroorganisme. Memperbaiki struktur tanah.',
    price: 45000,
    stock: 90,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 123,
  },
  {
    name: 'Sarung Tangan Berkebun',
    description: 'Sarung tangan karet tebal anti tembus. Nyaman dipakai lama. Melindungi tangan dari duri dan kotoran.',
    price: 25000,
    stock: 100,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 145,
  },
  {
    name: 'Sekam Bakar 5kg',
    description: 'Media tanam sekam bakar steril. Ringan dan porous. Bagus untuk campuran media tanam atau mulsa.',
    price: 20000,
    stock: 130,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 167,
  },
  {
    name: 'Pot Taman Gantung Set 3pcs',
    description: 'Set 3 pot gantung dengan hanger. Desain cantik untuk dekorasi taman atau teras. Bahan plastik kuat.',
    price: 95000,
    stock: 48,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 62,
  },
  {
    name: 'Pupuk Daun Cair 500ml',
    description: 'Pupuk daun lengkap untuk pertumbuhan maksimal. Spray langsung ke daun. Hasil terlihat dalam 3-7 hari.',
    price: 38000,
    stock: 110,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 142,
  },
  {
    name: 'Cangkul Mini Taman',
    description: 'Cangkul mini untuk taman dan pot. Ringan dan mudah digunakan. Stainless steel berkualitas.',
    price: 58000,
    stock: 62,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 71,
  },
  {
    name: 'Polybag Set 50pcs 30cm',
    description: 'Set 50 polybag ukuran 30cm. Kuat dan tahan lama. Cocok untuk tanaman berukuran sedang hingga besar.',
    price: 42000,
    stock: 95,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 108,
  },
  {
    name: 'Pupuk Bokashi 3kg',
    description: 'Pupuk bokashi fermentasi EM4. Mempercepat pertumbuhan dan meningkatkan hasil panen. Organik 100%.',
    price: 32000,
    stock: 125,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 151,
  },
  {
    name: 'Selang Air Taman 20m',
    description: 'Selang air fleksibel 20 meter. Dilengkapi nozzle multi fungsi. Tahan UV dan tidak mudah pecah.',
    price: 85000,
    stock: 40,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 52,
  },
  {
    name: 'Ajir Bambu Set 50pcs',
    description: 'Set 50 ajir bambu panjang 60cm. Untuk penyangga tanaman merambat. Kuat dan tahan lama.',
    price: 28000,
    stock: 88,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1523301551780-cd17359a95d0?w=800'],
    sellerId: 'seller4@example.com',
    sellerName: 'Tani Makmur',
    sellerRating: 4.6,
    sellerLocation: 'Yogyakarta',
    sold: 94,
  },
  {
    name: 'Pot Terakota 25cm',
    description: 'Pot terakota alami ukuran 25cm. Breathable untuk akar tanaman. Desain klasik yang timeless.',
    price: 72000,
    stock: 52,
    category: 'peralatan',
    images: ['https://images.unsplash.com/photo-1485955900006-10f4d324d411?w=800'],
    sellerId: 'seller5@example.com',
    sellerName: 'Kebun Organik',
    sellerRating: 4.8,
    sellerLocation: 'Bogor',
    sold: 68,
  },
];

// ==================== SEED FUNCTIONS ====================

// Function to seed users
async function seedUsers() {
  let successCount = 0;
  for (const userData of sampleUsers) {
    try {
      if (userData.role === 'admin') {
        await userAPI.register(userData.email, userData.password, userData.name);
      } else if (userData.role === 'seller' && userData.hasSellerAccount) {
        // Register as buyer first
        await userAPI.register(userData.email, userData.password, userData.name);
        // Then apply as seller
        await userAPI.applySeller(userData.email, {
          shopName: userData.shopName,
          shopDescription: userData.shopDescription,
          address: userData.shopAddress,
          city: userData.shopCity,
          phone: userData.phone,
        });
      } else {
        // Register as buyer
        await userAPI.register(userData.email, userData.password, userData.name);
      }
      successCount++;
    } catch (error) {
      console.log('User might already exist:', userData.email);
    }
  }
  console.log(`✅ Seeded ${successCount} users`);
}

// Function to seed products
async function seedProducts() {
  let successCount = 0;
  for (const product of sampleProducts) {
    try {
      await productAPI.create(product);
      successCount++;
    } catch (error) {
      console.log('Product might already exist:', product.name);
    }
  }
  console.log(`✅ Seeded ${successCount} products`);
}

// Function to seed sample orders
async function seedSampleOrders() {
  let successCount = 0;
  const sampleOrders = [
    {
      buyerEmail: 'buyer1@example.com',
      buyerName: 'Andi Kurniawan',
      items: [
        {
          productId: 'product_monstera_deliciosa',
          productName: 'Monstera Deliciosa',
          price: 150000,
          quantity: 1,
          sellerId: 'seller1@example.com',
          sellerName: 'Toko Tanaman Hijau',
        },
      ],
      total: 165000,
      shippingCost: 15000,
      paymentMethod: 'cod',
      shippingAddress: {
        name: 'Andi Kurniawan',
        phone: '081111222333',
        address: 'Jl. Sudirman No. 12',
        city: 'Jakarta Pusat',
      },
      status: 'delivered',
      paymentStatus: 'cod',
      notes: 'Pesanan pertama saya, puas dengan pelayanan!',
    },
    {
      buyerEmail: 'buyer2@example.com',
      buyerName: 'Maya Sari',
      items: [
        {
          productId: 'product_sansevieria',
          productName: 'Sansevieria Trifasciata',
          price: 85000,
          quantity: 2,
          sellerId: 'seller2@example.com',
          sellerName: 'Green Paradise',
        },
      ],
      total: 185000,
      shippingCost: 15000,
      paymentMethod: 'transfer',
      shippingAddress: {
        name: 'Maya Sari',
        phone: '082222333444',
        address: 'Jl. Gatot Subroto No. 45',
        city: 'Jakarta Selatan',
      },
      status: 'in_delivery',
      paymentStatus: 'paid',
      notes: 'Tolong packing yang rapi ya',
    },
    {
      buyerEmail: 'buyer3@example.com',
      buyerName: 'Rizky Pratama',
      items: [
        {
          productId: 'product_benih_tomat',
          productName: 'Benih Tomat Cherry',
          price: 25000,
          quantity: 3,
          sellerId: 'seller3@example.com',
          sellerName: 'Benih Nusantara',
        },
        {
          productId: 'product_pupuk_kompos',
          productName: 'Pupuk Organik Kompos 5kg',
          price: 35000,
          quantity: 2,
          sellerId: 'seller5@example.com',
          sellerName: 'Kebun Organik',
        },
      ],
      total: 155000,
      shippingCost: 20000,
      paymentMethod: 'e-wallet',
      shippingAddress: {
        name: 'Rizky Pratama',
        phone: '083333444555',
        address: 'Jl. Dago No. 78',
        city: 'Bandung',
      },
      status: 'confirmed',
      paymentStatus: 'paid',
    },
  ];

  for (const orderData of sampleOrders) {
    try {
      await orderAPI.create(orderData);
      successCount++;
    } catch (error) {
      console.log('Sample order creation failed:', error);
    }
  }
  console.log(`✅ Seeded ${successCount} sample orders`);
}

// Function to seed chat conversations
async function seedSampleChats() {
  let successCount = 0;
  const sampleChats = [
    {
      buyerId: 'buyer1@example.com',
      sellerId: 'seller1@example.com',
      productId: 'product_monstera_deliciosa',
      initialMessages: [
        {
          sender: 'buyer1@example.com',
          text: 'Halo kak, tanamannya masih ready?',
        },
        {
          sender: 'seller1@example.com',
          text: 'Halo! Masih ready kak. Mau berapa pot?',
        },
        {
          sender: 'buyer1@example.com',
          text: 'Saya ambil 1 dulu kak, buat coba. Kalau cocok nanti order lagi.',
        },
        {
          sender: 'seller1@example.com',
          text: 'Siap kak! Langsung checkout aja ya. Terima kasih 🙏',
        },
      ],
    },
    {
      buyerId: 'buyer2@example.com',
      sellerId: 'seller2@example.com',
      productId: 'product_sansevieria',
      initialMessages: [
        {
          sender: 'buyer2@example.com',
          text: 'Kak, itu tanaman lidah mertua bisa untuk di ruang AC kan?',
        },
        {
          sender: 'seller2@example.com',
          text: 'Bisa banget kak! Tanaman ini sangat cocok untuk ruang ber-AC. Justru dia suka suhu sejuk.',
        },
        {
          sender: 'buyer2@example.com',
          text: 'Oke siap, saya order 2 pot ya kak',
        },
      ],
    },
    {
      buyerId: 'buyer3@example.com',
      sellerId: 'seller3@example.com',
      productId: 'product_benih_tomat',
      initialMessages: [
        {
          sender: 'buyer3@example.com',
          text: 'Mas, benih tomatnya cocok ga untuk ditanam di pot?',
        },
        {
          sender: 'seller3@example.com',
          text: 'Cocok banget mas! Tomat cherry ini memang ideal untuk pot. Ukuran pot minimal 30cm ya.',
        },
        {
          sender: 'buyer3@example.com',
          text: 'Oke makasih infonya. Kalau pupuknya ada rekomendasi ga?',
        },
        {
          sender: 'seller3@example.com',
          text: 'Pakai pupuk kompos aja mas, organic dan aman. Ada di toko sebelah hehe',
        },
      ],
    },
  ];

  for (const chatData of sampleChats) {
    try {
      const { chat } = await chatAPI.getOrCreate(chatData.buyerId, chatData.sellerId, chatData.productId);
      
      // Add messages
      for (const msg of chatData.initialMessages) {
        await chatAPI.sendMessage(chat.id, {
          sender: msg.sender,
          text: msg.text,
        });
      }
      
      successCount++;
    } catch (error) {
      console.log('Sample chat creation failed:', error);
    }
  }
  console.log(`✅ Seeded ${successCount} chat conversations`);
}

// Main seed function
export async function seedInitialData() {
  try {
    console.log('🌱 Seeding initial data...');
    
    await seedUsers();
    await seedProducts();
    await seedSampleOrders();
    await seedSampleChats();
    
    console.log('🎉 Initial data seeding completed!');
    return true;
  } catch (error) {
    console.error('❌ Error seeding data:', error);
    return false;
  }
}

// Check if database needs seeding
export async function checkAndSeedData() {
  try {
    const { products } = await productAPI.getAll();
    
    // If few products exist, seed the database
    if (!products || products.length < 10) {
      console.log('Database needs seeding. Starting seed process...');
      await seedInitialData();
    } else {
      console.log(`Database already has ${products.length} products`);
    }
  } catch (error) {
    console.error('Error checking database:', error);
    // If there's an error fetching products, try seeding anyway
    await seedInitialData();
  }
}
